// Every country on earth with default language and measurement system
export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', language: 'Pashto', unit: 'metric' },
  { code: 'AX', name: 'Åland Islands', language: 'Swedish', unit: 'metric' },
  { code: 'AL', name: 'Albania', language: 'Albanian', unit: 'metric' },
  { code: 'DZ', name: 'Algeria', language: 'Arabic', unit: 'metric' },
  { code: 'AS', name: 'American Samoa', language: 'English', unit: 'imperial' },
  { code: 'AD', name: 'Andorra', language: 'Catalan', unit: 'metric' },
  { code: 'AO', name: 'Angola', language: 'Portuguese', unit: 'metric' },
  { code: 'AI', name: 'Anguilla', language: 'English', unit: 'metric' },
  { code: 'AQ', name: 'Antarctica', language: 'English', unit: 'metric' },
  { code: 'AG', name: 'Antigua and Barbuda', language: 'English', unit: 'metric' },
  { code: 'AR', name: 'Argentina', language: 'Spanish', unit: 'metric' },
  { code: 'AM', name: 'Armenia', language: 'Armenian', unit: 'metric' },
  { code: 'AW', name: 'Aruba', language: 'Papiamento', unit: 'metric' },
  { code: 'AU', name: 'Australia', language: 'English', unit: 'metric' },
  { code: 'AT', name: 'Austria', language: 'German', unit: 'metric' },
  { code: 'AZ', name: 'Azerbaijan', language: 'Azerbaijani', unit: 'metric' },
  { code: 'BS', name: 'Bahamas', language: 'English', unit: 'metric' },
  { code: 'BH', name: 'Bahrain', language: 'Arabic', unit: 'metric' },
  { code: 'BD', name: 'Bangladesh', language: 'Bengali', unit: 'metric' },
  { code: 'BB', name: 'Barbados', language: 'English', unit: 'metric' },
  { code: 'BY', name: 'Belarus', language: 'Belarusian', unit: 'metric' },
  { code: 'BE', name: 'Belgium', language: 'Dutch', unit: 'metric' },
  { code: 'BZ', name: 'Belize', language: 'English', unit: 'metric' },
  { code: 'BJ', name: 'Benin', language: 'French', unit: 'metric' },
  { code: 'BM', name: 'Bermuda', language: 'English', unit: 'metric' },
  { code: 'BT', name: 'Bhutan', language: 'Dzongkha', unit: 'metric' },
  { code: 'BO', name: 'Bolivia', language: 'Spanish', unit: 'metric' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', language: 'Dutch', unit: 'metric' },
  { code: 'BA', name: 'Bosnia and Herzegovina', language: 'Bosnian', unit: 'metric' },
  { code: 'BW', name: 'Botswana', language: 'English', unit: 'metric' },
  { code: 'BV', name: 'Bouvet Island', language: 'Norwegian', unit: 'metric' },
  { code: 'BR', name: 'Brazil', language: 'Portuguese', unit: 'metric' },
  { code: 'IO', name: 'British Indian Ocean Territory', language: 'English', unit: 'metric' },
  { code: 'BN', name: 'Brunei Darussalam', language: 'Malay', unit: 'metric' },
  { code: 'BG', name: 'Bulgaria', language: 'Bulgarian', unit: 'metric' },
  { code: 'BF', name: 'Burkina Faso', language: 'French', unit: 'metric' },
  { code: 'BI', name: 'Burundi', language: 'Kirundi', unit: 'metric' },
  { code: 'CV', name: 'Cabo Verde', language: 'Portuguese', unit: 'metric' },
  { code: 'KH', name: 'Cambodia', language: 'Khmer', unit: 'metric' },
  { code: 'CM', name: 'Cameroon', language: 'French', unit: 'metric' },
  { code: 'CA', name: 'Canada', language: 'English', unit: 'metric' },
  { code: 'KY', name: 'Cayman Islands', language: 'English', unit: 'metric' },
  { code: 'CF', name: 'Central African Republic', language: 'French', unit: 'metric' },
  { code: 'TD', name: 'Chad', language: 'French', unit: 'metric' },
  { code: 'CL', name: 'Chile', language: 'Spanish', unit: 'metric' },
  { code: 'CN', name: 'China', language: 'Mandarin Chinese', unit: 'metric' },
  { code: 'CX', name: 'Christmas Island', language: 'English', unit: 'metric' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', language: 'English', unit: 'metric' },
  { code: 'CO', name: 'Colombia', language: 'Spanish', unit: 'metric' },
  { code: 'KM', name: 'Comoros', language: 'Comorian', unit: 'metric' },
  { code: 'CD', name: 'Congo (DRC)', language: 'French', unit: 'metric' },
  { code: 'CG', name: 'Congo (Republic)', language: 'French', unit: 'metric' },
  { code: 'CK', name: 'Cook Islands', language: 'English', unit: 'metric' },
  { code: 'CR', name: 'Costa Rica', language: 'Spanish', unit: 'metric' },
  { code: 'HR', name: 'Croatia', language: 'Croatian', unit: 'metric' },
  { code: 'CU', name: 'Cuba', language: 'Spanish', unit: 'metric' },
  { code: 'CW', name: 'Curaçao', language: 'Papiamento', unit: 'metric' },
  { code: 'CY', name: 'Cyprus', language: 'Greek', unit: 'metric' },
  { code: 'CZ', name: 'Czech Republic', language: 'Czech', unit: 'metric' },
  { code: 'DK', name: 'Denmark', language: 'Danish', unit: 'metric' },
  { code: 'DJ', name: 'Djibouti', language: 'French', unit: 'metric' },
  { code: 'DM', name: 'Dominica', language: 'English', unit: 'metric' },
  { code: 'DO', name: 'Dominican Republic', language: 'Spanish', unit: 'metric' },
  { code: 'EC', name: 'Ecuador', language: 'Spanish', unit: 'metric' },
  { code: 'EG', name: 'Egypt', language: 'Arabic', unit: 'metric' },
  { code: 'SV', name: 'El Salvador', language: 'Spanish', unit: 'metric' },
  { code: 'GQ', name: 'Equatorial Guinea', language: 'Spanish', unit: 'metric' },
  { code: 'ER', name: 'Eritrea', language: 'Tigrinya', unit: 'metric' },
  { code: 'EE', name: 'Estonia', language: 'Estonian', unit: 'metric' },
  { code: 'SZ', name: 'Eswatini', language: 'Swati', unit: 'metric' },
  { code: 'ET', name: 'Ethiopia', language: 'Amharic', unit: 'metric' },
  { code: 'FK', name: 'Falkland Islands', language: 'English', unit: 'metric' },
  { code: 'FO', name: 'Faroe Islands', language: 'Faroese', unit: 'metric' },
  { code: 'FJ', name: 'Fiji', language: 'Fijian', unit: 'metric' },
  { code: 'FI', name: 'Finland', language: 'Finnish', unit: 'metric' },
  { code: 'FR', name: 'France', language: 'French', unit: 'metric' },
  { code: 'GF', name: 'French Guiana', language: 'French', unit: 'metric' },
  { code: 'PF', name: 'French Polynesia', language: 'French', unit: 'metric' },
  { code: 'TF', name: 'French Southern Territories', language: 'French', unit: 'metric' },
  { code: 'GA', name: 'Gabon', language: 'French', unit: 'metric' },
  { code: 'GM', name: 'Gambia', language: 'English', unit: 'metric' },
  { code: 'GE', name: 'Georgia', language: 'Georgian', unit: 'metric' },
  { code: 'DE', name: 'Germany', language: 'German', unit: 'metric' },
  { code: 'GH', name: 'Ghana', language: 'English', unit: 'metric' },
  { code: 'GI', name: 'Gibraltar', language: 'English', unit: 'metric' },
  { code: 'GR', name: 'Greece', language: 'Greek', unit: 'metric' },
  { code: 'GL', name: 'Greenland', language: 'Greenlandic', unit: 'metric' },
  { code: 'GD', name: 'Grenada', language: 'English', unit: 'metric' },
  { code: 'GP', name: 'Guadeloupe', language: 'French', unit: 'metric' },
  { code: 'GU', name: 'Guam', language: 'English', unit: 'imperial' },
  { code: 'GT', name: 'Guatemala', language: 'Spanish', unit: 'metric' },
  { code: 'GG', name: 'Guernsey', language: 'English', unit: 'metric' },
  { code: 'GN', name: 'Guinea', language: 'French', unit: 'metric' },
  { code: 'GW', name: 'Guinea-Bissau', language: 'Portuguese', unit: 'metric' },
  { code: 'GY', name: 'Guyana', language: 'English', unit: 'metric' },
  { code: 'HT', name: 'Haiti', language: 'Haitian Creole', unit: 'metric' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', language: 'English', unit: 'metric' },
  { code: 'VA', name: 'Holy See (Vatican)', language: 'Italian', unit: 'metric' },
  { code: 'HN', name: 'Honduras', language: 'Spanish', unit: 'metric' },
  { code: 'HK', name: 'Hong Kong', language: 'Cantonese Chinese', unit: 'metric' },
  { code: 'HU', name: 'Hungary', language: 'Hungarian', unit: 'metric' },
  { code: 'IS', name: 'Iceland', language: 'Icelandic', unit: 'metric' },
  { code: 'IN', name: 'India', language: 'Hindi', unit: 'metric' },
  { code: 'ID', name: 'Indonesia', language: 'Indonesian', unit: 'metric' },
  { code: 'IR', name: 'Iran', language: 'Persian (Farsi)', unit: 'metric' },
  { code: 'IQ', name: 'Iraq', language: 'Arabic', unit: 'metric' },
  { code: 'IE', name: 'Ireland', language: 'English', unit: 'metric' },
  { code: 'IM', name: 'Isle of Man', language: 'English', unit: 'metric' },
  { code: 'IL', name: 'Israel', language: 'Hebrew', unit: 'metric' },
  { code: 'IT', name: 'Italy', language: 'Italian', unit: 'metric' },
  { code: 'CI', name: 'Ivory Coast', language: 'French', unit: 'metric' },
  { code: 'JM', name: 'Jamaica', language: 'English', unit: 'metric' },
  { code: 'JP', name: 'Japan', language: 'Japanese', unit: 'metric' },
  { code: 'JE', name: 'Jersey', language: 'English', unit: 'metric' },
  { code: 'JO', name: 'Jordan', language: 'Arabic', unit: 'metric' },
  { code: 'KZ', name: 'Kazakhstan', language: 'Kazakh', unit: 'metric' },
  { code: 'KE', name: 'Kenya', language: 'Swahili', unit: 'metric' },
  { code: 'KI', name: 'Kiribati', language: 'Gilbertese', unit: 'metric' },
  { code: 'KP', name: 'Korea (North)', language: 'Korean', unit: 'metric' },
  { code: 'KR', name: 'Korea (South)', language: 'Korean', unit: 'metric' },
  { code: 'XK', name: 'Kosovo', language: 'Albanian', unit: 'metric' },
  { code: 'KW', name: 'Kuwait', language: 'Arabic', unit: 'metric' },
  { code: 'KG', name: 'Kyrgyzstan', language: 'Kyrgyz', unit: 'metric' },
  { code: 'LA', name: 'Laos', language: 'Lao', unit: 'metric' },
  { code: 'LV', name: 'Latvia', language: 'Latvian', unit: 'metric' },
  { code: 'LB', name: 'Lebanon', language: 'Arabic', unit: 'metric' },
  { code: 'LS', name: 'Lesotho', language: 'Sesotho', unit: 'metric' },
  { code: 'LR', name: 'Liberia', language: 'English', unit: 'metric' },
  { code: 'LY', name: 'Libya', language: 'Arabic', unit: 'metric' },
  { code: 'LI', name: 'Liechtenstein', language: 'German', unit: 'metric' },
  { code: 'LT', name: 'Lithuania', language: 'Lithuanian', unit: 'metric' },
  { code: 'LU', name: 'Luxembourg', language: 'Luxembourgish', unit: 'metric' },
  { code: 'MO', name: 'Macao', language: 'Cantonese Chinese', unit: 'metric' },
  { code: 'MG', name: 'Madagascar', language: 'Malagasy', unit: 'metric' },
  { code: 'MW', name: 'Malawi', language: 'Chichewa', unit: 'metric' },
  { code: 'MY', name: 'Malaysia', language: 'Malay', unit: 'metric' },
  { code: 'MV', name: 'Maldives', language: 'Dhivehi', unit: 'metric' },
  { code: 'ML', name: 'Mali', language: 'French', unit: 'metric' },
  { code: 'MT', name: 'Malta', language: 'Maltese', unit: 'metric' },
  { code: 'MH', name: 'Marshall Islands', language: 'Marshallese', unit: 'imperial' },
  { code: 'MQ', name: 'Martinique', language: 'French', unit: 'metric' },
  { code: 'MR', name: 'Mauritania', language: 'Arabic', unit: 'metric' },
  { code: 'MU', name: 'Mauritius', language: 'Mauritian Creole', unit: 'metric' },
  { code: 'YT', name: 'Mayotte', language: 'French', unit: 'metric' },
  { code: 'MX', name: 'Mexico', language: 'Spanish', unit: 'metric' },
  { code: 'FM', name: 'Micronesia', language: 'English', unit: 'imperial' },
  { code: 'MD', name: 'Moldova', language: 'Romanian', unit: 'metric' },
  { code: 'MC', name: 'Monaco', language: 'French', unit: 'metric' },
  { code: 'MN', name: 'Mongolia', language: 'Mongolian', unit: 'metric' },
  { code: 'ME', name: 'Montenegro', language: 'Montenegrin', unit: 'metric' },
  { code: 'MS', name: 'Montserrat', language: 'English', unit: 'metric' },
  { code: 'MA', name: 'Morocco', language: 'Arabic', unit: 'metric' },
  { code: 'MZ', name: 'Mozambique', language: 'Portuguese', unit: 'metric' },
  { code: 'MM', name: 'Myanmar (Burma)', language: 'Burmese', unit: 'metric' },
  { code: 'NA', name: 'Namibia', language: 'English', unit: 'metric' },
  { code: 'NR', name: 'Nauru', language: 'Nauruan', unit: 'metric' },
  { code: 'NP', name: 'Nepal', language: 'Nepali', unit: 'metric' },
  { code: 'NL', name: 'Netherlands', language: 'Dutch', unit: 'metric' },
  { code: 'NC', name: 'New Caledonia', language: 'French', unit: 'metric' },
  { code: 'NZ', name: 'New Zealand', language: 'English', unit: 'metric' },
  { code: 'NI', name: 'Nicaragua', language: 'Spanish', unit: 'metric' },
  { code: 'NE', name: 'Niger', language: 'French', unit: 'metric' },
  { code: 'NG', name: 'Nigeria', language: 'English', unit: 'metric' },
  { code: 'NU', name: 'Niue', language: 'Niuean', unit: 'metric' },
  { code: 'NF', name: 'Norfolk Island', language: 'English', unit: 'metric' },
  { code: 'MK', name: 'North Macedonia', language: 'Macedonian', unit: 'metric' },
  { code: 'MP', name: 'Northern Mariana Islands', language: 'English', unit: 'imperial' },
  { code: 'NO', name: 'Norway', language: 'Norwegian', unit: 'metric' },
  { code: 'OM', name: 'Oman', language: 'Arabic', unit: 'metric' },
  { code: 'PK', name: 'Pakistan', language: 'Urdu', unit: 'metric' },
  { code: 'PW', name: 'Palau', language: 'Palauan', unit: 'imperial' },
  { code: 'PS', name: 'Palestine', language: 'Arabic', unit: 'metric' },
  { code: 'PA', name: 'Panama', language: 'Spanish', unit: 'metric' },
  { code: 'PG', name: 'Papua New Guinea', language: 'Tok Pisin', unit: 'metric' },
  { code: 'PY', name: 'Paraguay', language: 'Spanish', unit: 'metric' },
  { code: 'PE', name: 'Peru', language: 'Spanish', unit: 'metric' },
  { code: 'PH', name: 'Philippines', language: 'Filipino', unit: 'metric' },
  { code: 'PN', name: 'Pitcairn Islands', language: 'English', unit: 'metric' },
  { code: 'PL', name: 'Poland', language: 'Polish', unit: 'metric' },
  { code: 'PT', name: 'Portugal', language: 'Portuguese', unit: 'metric' },
  { code: 'PR', name: 'Puerto Rico', language: 'Spanish', unit: 'imperial' },
  { code: 'QA', name: 'Qatar', language: 'Arabic', unit: 'metric' },
  { code: 'RE', name: 'Réunion', language: 'French', unit: 'metric' },
  { code: 'RO', name: 'Romania', language: 'Romanian', unit: 'metric' },
  { code: 'RU', name: 'Russia', language: 'Russian', unit: 'metric' },
  { code: 'RW', name: 'Rwanda', language: 'Kinyarwanda', unit: 'metric' },
  { code: 'BL', name: 'Saint Barthélemy', language: 'French', unit: 'metric' },
  { code: 'SH', name: 'Saint Helena', language: 'English', unit: 'metric' },
  { code: 'KN', name: 'Saint Kitts and Nevis', language: 'English', unit: 'metric' },
  { code: 'LC', name: 'Saint Lucia', language: 'English', unit: 'metric' },
  { code: 'MF', name: 'Saint Martin (French)', language: 'French', unit: 'metric' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', language: 'French', unit: 'metric' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', language: 'English', unit: 'metric' },
  { code: 'WS', name: 'Samoa', language: 'Samoan', unit: 'metric' },
  { code: 'SM', name: 'San Marino', language: 'Italian', unit: 'metric' },
  { code: 'ST', name: 'São Tomé and Príncipe', language: 'Portuguese', unit: 'metric' },
  { code: 'SA', name: 'Saudi Arabia', language: 'Arabic', unit: 'metric' },
  { code: 'SN', name: 'Senegal', language: 'French', unit: 'metric' },
  { code: 'RS', name: 'Serbia', language: 'Serbian', unit: 'metric' },
  { code: 'SC', name: 'Seychelles', language: 'Seychellois Creole', unit: 'metric' },
  { code: 'SL', name: 'Sierra Leone', language: 'English', unit: 'metric' },
  { code: 'SG', name: 'Singapore', language: 'English', unit: 'metric' },
  { code: 'SX', name: 'Sint Maarten (Dutch)', language: 'Dutch', unit: 'metric' },
  { code: 'SK', name: 'Slovakia', language: 'Slovak', unit: 'metric' },
  { code: 'SI', name: 'Slovenia', language: 'Slovenian', unit: 'metric' },
  { code: 'SB', name: 'Solomon Islands', language: 'English', unit: 'metric' },
  { code: 'SO', name: 'Somalia', language: 'Somali', unit: 'metric' },
  { code: 'ZA', name: 'South Africa', language: 'Zulu', unit: 'metric' },
  { code: 'GS', name: 'South Georgia and South Sandwich Islands', language: 'English', unit: 'metric' },
  { code: 'SS', name: 'South Sudan', language: 'English', unit: 'metric' },
  { code: 'ES', name: 'Spain', language: 'Spanish', unit: 'metric' },
  { code: 'LK', name: 'Sri Lanka', language: 'Sinhala', unit: 'metric' },
  { code: 'SD', name: 'Sudan', language: 'Arabic', unit: 'metric' },
  { code: 'SR', name: 'Suriname', language: 'Dutch', unit: 'metric' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', language: 'Norwegian', unit: 'metric' },
  { code: 'SE', name: 'Sweden', language: 'Swedish', unit: 'metric' },
  { code: 'CH', name: 'Switzerland', language: 'German', unit: 'metric' },
  { code: 'SY', name: 'Syria', language: 'Arabic', unit: 'metric' },
  { code: 'TW', name: 'Taiwan', language: 'Mandarin Chinese', unit: 'metric' },
  { code: 'TJ', name: 'Tajikistan', language: 'Tajik', unit: 'metric' },
  { code: 'TZ', name: 'Tanzania', language: 'Swahili', unit: 'metric' },
  { code: 'TH', name: 'Thailand', language: 'Thai', unit: 'metric' },
  { code: 'TL', name: 'Timor-Leste', language: 'Tetum', unit: 'metric' },
  { code: 'TG', name: 'Togo', language: 'French', unit: 'metric' },
  { code: 'TK', name: 'Tokelau', language: 'Tokelauan', unit: 'metric' },
  { code: 'TO', name: 'Tonga', language: 'Tongan', unit: 'metric' },
  { code: 'TT', name: 'Trinidad and Tobago', language: 'English', unit: 'metric' },
  { code: 'TN', name: 'Tunisia', language: 'Arabic', unit: 'metric' },
  { code: 'TR', name: 'Turkey', language: 'Turkish', unit: 'metric' },
  { code: 'TM', name: 'Turkmenistan', language: 'Turkmen', unit: 'metric' },
  { code: 'TC', name: 'Turks and Caicos Islands', language: 'English', unit: 'metric' },
  { code: 'TV', name: 'Tuvalu', language: 'Tuvaluan', unit: 'metric' },
  { code: 'UG', name: 'Uganda', language: 'English', unit: 'metric' },
  { code: 'UA', name: 'Ukraine', language: 'Ukrainian', unit: 'metric' },
  { code: 'AE', name: 'United Arab Emirates', language: 'Arabic', unit: 'metric' },
  { code: 'GB', name: 'United Kingdom', language: 'English', unit: 'metric' },
  { code: 'US', name: 'United States', language: 'English', unit: 'imperial' },
  { code: 'UM', name: 'United States Minor Outlying Islands', language: 'English', unit: 'imperial' },
  { code: 'UY', name: 'Uruguay', language: 'Spanish', unit: 'metric' },
  { code: 'UZ', name: 'Uzbekistan', language: 'Uzbek', unit: 'metric' },
  { code: 'VU', name: 'Vanuatu', language: 'Bislama', unit: 'metric' },
  { code: 'VE', name: 'Venezuela', language: 'Spanish', unit: 'metric' },
  { code: 'VN', name: 'Vietnam', language: 'Vietnamese', unit: 'metric' },
  { code: 'VG', name: 'Virgin Islands (British)', language: 'English', unit: 'metric' },
  { code: 'VI', name: 'Virgin Islands (U.S.)', language: 'English', unit: 'imperial' },
  { code: 'WF', name: 'Wallis and Futuna', language: 'French', unit: 'metric' },
  { code: 'EH', name: 'Western Sahara', language: 'Arabic', unit: 'metric' },
  { code: 'YE', name: 'Yemen', language: 'Arabic', unit: 'metric' },
  { code: 'ZM', name: 'Zambia', language: 'English', unit: 'metric' },
  { code: 'ZW', name: 'Zimbabwe', language: 'English', unit: 'metric' },
];

// Every language spoken on earth (major + minority + indigenous)
export const LANGUAGES = [
  'Abkhaz', 'Acehnese', 'Acholi', 'Afar', 'Afrikaans', 'Ainu', 'Akan', 'Albanian',
  'Aleut', 'Amharic', 'Arabic', 'Aragonese', 'Aramaic', 'Armenian', 'Aromanian',
  'Assamese', 'Asturian', 'Avar', 'Aymara', 'Azerbaijani',
  'Balinese', 'Bambara', 'Bashkir', 'Basque', 'Belarusian', 'Bengali', 'Berber (Tamazight)',
  'Bhojpuri', 'Bislama', 'Bosnian', 'Breton', 'Bulgarian', 'Burmese',
  'Cantonese Chinese', 'Catalan', 'Cebuano', 'Chechen', 'Cherokee', 'Chewa (Chichewa)',
  'Chichewa', 'Chuvash', 'Comorian', 'Cornish', 'Corsican', 'Croatian', 'Czech',
  'Danish', 'Dari', 'Dhivehi', 'Dinka', 'Dutch', 'Dzongkha',
  'English', 'Esperanto', 'Estonian', 'Ewe',
  'Faroese', 'Fijian', 'Filipino', 'Finnish', 'Flemish', 'French', 'Fula (Fulani)',
  'Galician', 'Ganda (Luganda)', 'Georgian', 'German', 'Gilbertese', 'Greek',
  'Greenlandic (Kalaallisut)', 'Guaraní', 'Gujarati',
  'Haitian Creole', 'Hausa', 'Hawaiian', 'Hebrew', 'Hindi', 'Hmong', 'Hungarian',
  'Icelandic', 'Igbo', 'Ilocano', 'Indonesian', 'Inuktitut', 'Irish (Gaelic)', 'Italian',
  'Japanese', 'Javanese', 'Kannada', 'Kanuri', 'Kazakh', 'Khmer', 'Kinyarwanda',
  'Kirundi', 'Kongo', 'Korean', 'Kurdish (Kurmanji)', 'Kurdish (Sorani)', 'Kyrgyz',
  'Lao', 'Latin', 'Latvian', 'Lingala', 'Lithuanian', 'Luba-Kasai', 'Luxembourgish',
  'Macedonian', 'Malagasy', 'Malay', 'Malayalam', 'Maltese', 'Mandarin Chinese',
  'Maori', 'Marathi', 'Marshallese', 'Mauritian Creole', 'Min Nan Chinese', 'Moldovan',
  'Mongolian', 'Montenegrin',
  'Nahuatl', 'Nauruan', 'Navajo', 'Nepali', 'Niuean', 'Norwegian',
  'Occitan', 'Oriya (Odia)', 'Oromo', 'Ossetian',
  'Palauan', 'Papiamento', 'Pashto', 'Persian (Farsi)', 'Polish', 'Portuguese',
  'Punjabi',
  'Quechua',
  'Romanian', 'Romansh', 'Russian',
  'Samoan', 'Sanskrit', 'Scottish Gaelic', 'Serbian', 'Sesotho', 'Seychellois Creole',
  'Shona', 'Sindhi', 'Sinhala', 'Slovak', 'Slovenian', 'Somali', 'Sorani Kurdish',
  'Spanish', 'Sundanese', 'Swahili', 'Swati (Swazi)', 'Swedish',
  'Tagalog', 'Tajik', 'Tamil', 'Tatar', 'Telugu', 'Tetum', 'Thai', 'Tibetan',
  'Tigrinya', 'Tokelauan', 'Tok Pisin', 'Tongan', 'Tswana', 'Turkish', 'Turkmen',
  'Tuvaluan', 'Twi',
  'Ukrainian', 'Urdu', 'Uyghur', 'Uzbek',
  'Vietnamese',
  'Welsh', 'Wolof', 'Wu Chinese',
  'Xhosa',
  'Yiddish', 'Yoruba',
  'Zhuang', 'Zulu',
];

export function getCountryDefaults(countryCode) {
  const c = COUNTRIES.find(c => c.code === countryCode);
  return c ? { language: c.language, unit: c.unit } : { language: 'English', unit: 'imperial' };
}